# Generated by Django 4.2.30 on 2026-09-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('attendee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255)),
                ('feedback_data', models.JSONField(default=dict)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.OneToOneField(db_column='attendee_id', on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submission', to='feedback.attendee')),
            ],
            options={
                'db_table': 'feedback_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('max_spin_attempts', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form settings',
                'verbose_name_plural': 'Form settings',
                'db_table': 'form_settings',
            },
        ),
        migrations.CreateModel(
            name='LuckyDrawWinner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('drawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='feedback.feedbacksubmission')),
            ],
            options={
                'db_table': 'lucky_draw_winners',
                'ordering': ['-drawn_at'],
            },
        ),
    ]
