# Generated by Django 4.2.30 on 2026-09-22 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def clear_old_drawn_by(apps, schema_editor):
    # drawn_by pointed at django.contrib.auth users, those ids mean nothing in admin_users.
    apps.get_model("feedback", "LuckyDrawWinner").objects.update(drawn_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_users',
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='formsettings',
            name='spin_duration_seconds',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='feedback.adminuser')),
            ],
            options={
                'db_table': 'admin_tokens',
            },
        ),
        migrations.RunPython(clear_old_drawn_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='luckydrawwinner',
            name='drawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws', to='feedback.adminuser'),
        ),
    ]
